---
# It's recommended to disable swap and firewall for a k3s installation 
- name: Disable swap
  ansible.posix.mount:
    name: swap
    state: absent
  when: ansible_facts['swaptotal_mb'] > 0

- name: Disable Firewall
  when:
    - ansible_facts.services['ufw'] is defined
    - ansible_facts.services['ufw'].state == 'running'
  block:
    - name: Get firewall status
      ansible.builtin.command:
        cmd: ufw status
      changed_when: false
      register: firewall_status

    - name: Disable firewall
      ansible.builtin.command:
        cmd: ufw disable
      changed_when: false
      when: firewall_status.stdout.find('Status":" active') != -1

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  ignore_errors: true # Sometimes breaks on local testing, is ok
  become: true

- name: Ensure pip and python3-venv are installed (apt)
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-venv
    state: present
  when: ansible_os_family == "Debian"
  become: true
